name: Generate Snake

on:
  # Executa o workflow diariamente
  schedule:
    - cron: "0 0 * * *"
  # Executa o workflow sempre que um push é feito no repositório
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clonar Repositório
      uses: actions/checkout@v2
      with:
        repository: Platane/snk
        path: /tmp/snake
    
    - name: Gerar a Animação
      run: |
        cd /tmp/snake
        python3 generate.py --user JohannPDaniel --output ../

    - name: Adicionar a Animação ao Repositório
      uses: EndBug/add-and-commit@v9
      with:
        message: "Atualizar a animação de cobra"
        add: github-contribution-grid-snake.svg
  
