name: Generate Snake Animation

on:
  # Executa a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # Permite executar manualmente
  workflow_dispatch:
  # Executa quando um push é feito na branch principal
  push:
    branches:
      - main

jobs:
  generate_snake:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
    
    - name: Gerar a Animação de Cobra
      uses: Platane/snk@v3  # Usa uma versão estável
      with:
        github_user_name: JohannPDaniel  # Substitua pelo seu nome de usuário GitHub
        svg_out_path: github-contribution-grid-snake.svg  # Sem dist para melhor organização
    
    - name: Confirmar e Enviar a Animação
      uses: EndBug/add-and-commit@v9
      with:
        message: "Atualizar a animação de cobra"
        add: "github-contribution-grid-snake.svg"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  
