name: Generate Snake Animation

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
    
    - name: Gerar a Animação de Cobra
      uses: Platane/snk@v3  # Usa uma versão estável
      with:
        github_user_name: JohannPDaniel
        svg_out_path: github-contribution-grid-snake.svg
    
    - name: Confirmar e Enviar a Animação
      uses: EndBug/add-and-commit@v9
      with:
        message: "Atualizar a animação de cobra"
        add: "github-contribution-grid-snake.svg"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




  
